[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "lightshark-parser"
version = "1.0.0"
description = "A parser for Lightshark show files (.lshw)"
readme = "README.md"
requires-python = ">=3.7"


[project.scripts]
lightshark-parser = "lightshark_parser.main:main"


[tool.setuptools.packages.find]
where = ["."]
